# Generated by Django 4.0.6 on 2022-07-14 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=30)),
                ('monto', models.IntegerField()),
                ('acudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.acudiente')),
            ],
        ),
    ]
