# Generated by Django 4.0.6 on 2022-07-14 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_jugador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='monto',
            new_name='altura',
        ),
    ]
