# Generated by Django 4.0.6 on 2022-07-14 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_monto_jugador_altura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('entrenador', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jugador')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pago')),
            ],
        ),
    ]
