# Generated by Django 4.0.6 on 2022-08-06 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_jugador_equipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jugador',
            options={'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterModelOptions(
            name='subscripcion',
            options={'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscripciones'},
        ),
        migrations.CreateModel(
            name='Horario_partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partido', models.CharField(max_length=30)),
                ('uniforme', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='myapp.jugador')),
            ],
        ),
    ]
