# Generated by Django 4.0.6 on 2022-08-07 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_entrenamientos_jugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenamientos_jugador',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jugador'),
        ),
    ]
