# Generated by Django 4.0.6 on 2022-08-07 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_entrenamientos_jugador_jugador'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscripcion',
            new_name='Subcripcion',
        ),
    ]
