# Generated by Django 4.0.6 on 2022-08-07 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_subscripcion_subcripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='genero',
        ),
    ]
