# Generated by Django 4.0.6 on 2022-08-07 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_jugador_genero'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcripcion',
            new_name='Subscripcion',
        ),
    ]
