# Generated by Django 4.0.4 on 2022-08-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_subcripcion_subscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='genero',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
