# Generated by Django 4.0.4 on 2022-08-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_jugador_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='genero',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
