# Generated by Django 4.0.4 on 2022-08-11 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_jugador_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='genero',
        ),
    ]
