# Generated by Django 4.0.4 on 2022-08-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_jugador_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='gender',
            field=models.CharField(default='f', max_length=30, null=True),
        ),
    ]
