# Generated by Django 4.0.4 on 2022-08-11 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_jugador_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='gender',
        ),
    ]
