# Generated by Django 4.0.6 on 2022-08-17 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_jugador_genero_pago_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario_partido',
            name='primer_equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Horario_primer_equipo', to='myapp.equipo'),
        ),
        migrations.AddField(
            model_name='horario_partido',
            name='segundo_equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Horario_segundo_equipo', to='myapp.equipo'),
        ),
    ]
