# Generated by Django 4.1.1 on 2022-09-14 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_horario_partido_jugador_resultado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrenamientos_jugador',
            options={'verbose_name': 'Entrenamientos_jugador', 'verbose_name_plural': 'Entrenamientos_jugadores'},
        ),
    ]
