# Generated by Django 4.1.1 on 2022-09-14 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_jugador_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='acudiente',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='last_name',
        ),
    ]
